language: scala
scala:
   - 2.11.11
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
sbt_args: -no-colors
sudo: false
script: $HOME/script/test
after_success: "sbt coverageReport coveralls"
