language: scala
scala:
   - 2.11.11
jdk:
  - oraclejdk7
  - oraclejdk8

cache:
  directories:
  - $HOME/.ivy2/cache

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

#service_name: travis-pro
#repo_token: 7W6Sm1Hd5WraNDkx6yypKWBi1TgiBAIUw
